# Project information
site_name: 'Contributing'
site_description: 'Information on how to contribute to my projects'
site_author: 'Randy Rowland'
site_url: 'https://rowland007.github.io/Contributing/'

# Repository
repo_name: 'Randy Rowland'
repo_url: 'https://github.com/rowland007'

# Copyright
copyright: '&#127279; 2019 GNU General Public License v3.0'

# Navigation Menu
nav:
    - Home: 'index.md'
    - Contributing:
        'Introduction': 'contribute/index.md'
        'Forking': 'contribute/fork.md'
        'Branches': 'contribute/branch.md'
        'Code Signing': 'https://www.qubes-os.org/doc/code-signing/'
        'Commits': 'contribute/commit.md'
        'Pull Request': 'contribute/pull.md'
        'Bug Reports': 'contribute/bug.md'
        'Conclusion': 'static/page/construction.md'
    - Code Style Guide:
        'Introduction': 'style-guide/index.md'
        'Variables': 'style-guide/variables.md'
        'Functions': 'style-guide/functions.md'
        'Objects and Data Structures': 'style-guide/objects.md'
        'Classes': 'style-guide/classes.md'

# Configuration
theme:
    name: 'material'
    palette:
        primary: 'blue'
        accent: 'amber'
    logo:
        icon: 'people_alt'
    language: 'en'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

# Customization
extra:
    social:
        - type: 'github'
          link: 'https://github.com/rowland007'
        - type: 'twitter'
          link: 'https://twitter.com/randarxj7'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/in/randall-rowland-332a5039'
        - type: 'reddit-alien'
          link: 'https://www.reddit.com/user/rowland007'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
