# Project information
site_name: 'Contributing'
site_description: 'Information on how to contribute to my projects'
site_author: 'Randy Rowland'
site_url: 'https://rowland007.github.io/Contributing/'

# Repository
repo_name: 'Randy Rowland'
repo_url: 'https://github.com/rowland007'

# Copyright
copyright: 'Copyright &copy; 2019-2022 Randall Rowland<br>This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

# Navigation Menu
nav:
    - Home: 'index.md'
    - Contributing:
        'Introduction': 'contribute/index.md'
        'Forking': 'contribute/fork.md'
        'Branches': 'contribute/branch.md'
        'Code Signing': 'https://www.qubes-os.org/doc/code-signing/'
        'Commits': 'contribute/commit.md'
        'Pull Request': 'contribute/pull.md'
        'Bug Reports': 'contribute/bug.md'
    - Code Style Guide:
        'Introduction': 'style-guide/index.md'
        'Variables': 'style-guide/variables.md'
        'Functions': 'style-guide/functions.md'
        'Objects and Data Structures': 'style-guide/objects.md'
        'Classes': 'style-guide/classes.md'

# Configuration
theme:
  name: material
  palette:
    primary: blue
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/certificate

# Customization
extra:
  social:
    - icon: material/cloud
      link: https://randyrowland.me
    - icon: fontawesome/brands/github
      link: https://github.com/rowland007
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/randarxj7
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/randall-rowland-jr
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/user/rowland007

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
