site_name: Contributing
nav:
    - Home: 'index.md'
    - Contributing:
        'Introduction': 'contribute/index.md'
        'Forking': 'contribute/fork.md'
    - Code Style Guide:
        'style-guide/index.md'
theme: readthedocs