site_name: Contributing
nav:
    - Home: 'index.md'
    - Contributing:
        'Introduction': 'contribute/index.md'
        'Forking': 'contribute/fork.md'
        'Branches': 'static/page/construction.md'
        'Code Signing': 'https://www.qubes-os.org/doc/code-signing/'
        'Commits': 'contribute/commit.md'
        'Pull Request': 'static/page/construction.md'
        'Bug Reports': 'static/page/construction.md'
        'Conclusion': 'static/page/construction.md'
    - Code Style Guide:
        'Introduction': 'style-guide/index.md'
theme: readthedocs